%Annika Rings, September 2019
%
%ODOURSTIM
%

function odourstim(foldername, varargin)

arguments = varargin;
%check if we really want 11 frames after pulse
options = struct('framerate', 5.92, ...
    'baseline', 6, ...
    'after_pulse', 11, ...
    'odours', {{'ethanol'; 'acetic'}}, ...
    'genders', {{'_male'; 'female'; 'matedFemale'}}, ...
    'neuronparts', {{'medial'; 'lateral'}}, ...
    'resultsdir', 'Results', ...
    'multiroi', false, ...
    'numrois', 1, ...
    'roinames', {{}}, ...
    'inhibitor_conc', [0], ...
    'inhibitor_unit', 'uM', ...
    'inhibitor_names', {{'PTX'}}, ...
    'subfoldername', 'ROI', ...
    'stimdir', 'stim', ...
    'protocolname', '', ...
    'firstpulse', false, ...
    'pulseframe', 81, ...
    'eventdur', 180, ...
    'parallelize', true, ... % requires parallel computing toolbox
    'use_fluo', false, ...
    'stabilized', true);
%------------------------------------------------------------------------
%setting optional key-value pair arguments
%-------------------------------------------------------------------------

%call the options_resolver function to check optional key-value pair
%arguments
[options, ~] = options_resolver(options, arguments, 'odourstim');


analyse_fluo_stim(foldername, ...
    'framerate', options.framerate, ...
    'baseline', options.baseline, ...
    'after_pulse', options.after_pulse, ...
    'protocols', options.odours, ...
    'genders', options.genders, ...
    'neuronparts', options.neuronparts, ...
    'resultsdir', options.resultsdir, ...
    'multiroi', options.multiroi, ...
    'numrois', options.numrois, ...
    'roinames', options.roinames, ...
    'inhibitor_conc', options.inhibitor_conc, ...
    'inhibitor_unit', options.inhibitor_unit, ...
    'inhibitor_names', options.inhibitor_names, ...
    'subfoldername', options.subfoldername, ...
    'stimdir', options.stimdir, ...
    'protocolname', options.protocolname, ...
    'firstpulse', options.firstpulse, ...
    'pulseframe', options.pulseframe, ...
    'eventdur', options.eventdur, ...
    'parallelize', options.parallelize, ... % requires parallel computing toolbox
    'use_fluo', options.use_fluo, ...
    'stabilized', options.stabilized, ...
    'stimtype', 'odour', ...
    'stimintensity', 200);
